### ISSUE TITLE
Terrible noise when using built-in DAC

### ISSUE THREAD

**Issue by Bartvelp** [atomic14/esp32-play-mp3-demo#1]
Hi it's me again,
I wanted to look into using the DAC for output, but the output is terribly noisy. The song is almost inaudible. I have connected just the right channel using pin 25. I followed your schematic and added a capacitor of 100 uF with low ESR, and an resistor of 600 ohms. This gives terrible noise, omitting one or all of these components, the noise is just the same.
I added an audio sample (in zip because of github policy), as you can hear, it sounds horrid and the sample in your video sounded a lot better.
[WhatsApp Audio 2021-12-04 at 11.33.49.zip](https://github.com/atomic14/esp32-play-mp3-demo/files/7653764/WhatsApp.Audio.2021-12-04.at.11.33.49.zip)

What did I do wrong? my config.h
```c
#include <freertos/FreeRTOS.h>
#include <driver/i2s.h>

// comment this out if you want to use the internal DAC
// #define USE_I2S

// speaker settings - if using I2S
#define I2S_SPEAKER_SERIAL_CLOCK GPIO_NUM_19
#define I2S_SPEAKER_LEFT_RIGHT_CLOCK GPIO_NUM_21
#define I2S_SPEAKER_SERIAL_DATA GPIO_NUM_18
#define I2S_SPEAKDER_SD_PIN GPIO_NUM_5

// volume control - if required
// #define VOLUME_CONTROL ADC1_CHANNEL_7

// button - GPIO 0 is the built in button on most dev boards
#define GPIO_BUTTON GPIO_NUM_0

// i2s speaker pins definition
extern i2s_pin_config_t i2s_speaker_pins;
```

That's the only thing I changed next to the upload port

**Comment by cgreening** [comment]
That's pretty bad - I did get similar noise, but nowhere near as bad as that. It really depends on the quality of your board and the power supply as far as I can tell.

You can try a couple of things.

Add some capacitors across the power 3.3v and GND pins of the board - this may help a little bit.

You can also try powering the board from a "clean" power supply - e.g. a battery.

If you just connect the headphones directly to the output pins you should get a much louder output which can drown out the clicks.

The other option is to add a low pass filter to the output which will filter out some of the clicks.

**Comment by Bartvelp** [comment]
Thanks for your comment, turns out it was a silly mistake. Apparently I have a pin marked GND on my devboard, which infact is not ground. After connecting it to a proper GND pin, the noise was eliminated, and there only was some distortion of the lower tones, which was gone after omitting the capacitor, now the sound is honestly very good!
Thanks for you work in ESP32 sound, it still is all a bit over my head but I'm learning!

**Comment by cgreening** [comment]
That's awesome! Once you get into analogue audio circuits it's very much black magic. Things like ground loops and mains hum. It's a nightmare :)
