### ISSUE TITLE
no audio with esp-idf 4.4.1 when using the internal DAC

### ISSUE THREAD

**Issue by dlavrantonis** [atomic14/esp32-play-mp3-demo#3]
For the internal DAC example to work, lib/audio_output/src/DACOutput.cpp line 12 needs to be changed to:

        .communication_format = I2S_COMM_FORMAT_STAND_MSB,

Assuming that this was working in previous releases, it looks like esp-idf changed its behaviour and now you need to explicitly tell the i2s to use the 8 most significant bits from the 16 bits per sample? Maybe..

**Comment by cgreening** [comment]
Can you open a pull request for the change and I'll merge it in.

Thanks!

**Comment by cgreening** [comment]
This should now be merged.
