### ISSUE TITLE
Question about playing back higher bitrate songs

### ISSUE THREAD

**Issue by ahemberger** [atomic14/esp32-play-mp3-demo#5]
Hi! I've watched your video for this bit of code nearly a dozen times, and am finding it very helpful to learn from! 

One thing I notice is that I can get playback to work great using the audio clip you provide (which is encoded at 112kbps), but a different audio clip I have here (encoded at 192kbps) plays back choppily. After some experimentation, I've learned that increasing the DMA buffer count in the i2s config seems to play smoothly for a couple of seconds, but then the choppiness returns. I suspect this indicates I'm not buffering all this data right, and not feeing the i2s stream fast enough (I also tried speeding up the clock frequency on my esp32, but that made no difference, so I think my problem lies elsewhere). 

There are a lot of little buffering steps going on here, and while I'm trying to understand them all, it's a bit fuzzy for me. I wonder if you might have any intuition or advice for what you might adjust if you were trying to play a higher-bitrate mp3? 

Thanks!

**Comment by cgreening** [comment]
Reading from SPIFFS is very slow - so I suspect that will be where your problem is. It's probably not possible to read quickly enough.

Or, it might be that 192Kbps is too much work for the CPU and it can't decode quickly enough.

But my suspicion would be the SPIFFS speed.

I need to revisit this code and get it working with an SDCard.

**Comment by ahemberger** [comment]
Thank you so much!

Actually, I neglected to mention that I AM actually reading from an SD card - by default it's configured to run at 20MHz, which I *think* should be fast enough. 

But, taking a break and having a coffee this morning led me to wonder if maybe something to try is decoding things in bigger batches - it seems like right now we 'nibble' at the file very frequently, decoding a frame and then re-topping the buffer in small bites. I wonder if reading/decoding in larger chunks would be something to try (I'm using an esp32-s3, with 8mb PSRAM, so I think I should have ample room to try this).

**Comment by ahemberger** [comment]
Ah, I think I might have found my issue. I was creating my playback task thusly:
    xTaskCreate(playback_task, "playback_task", 32768, NULL, tskIDLE_PRIORITY, NULL);


Modifying this to match your code:
    xTaskCreatePinnedToCore(playback_task, "playback_task", 32768, NULL, 1, NULL, 1);

(which I think implies I had been previously running this on Core 0, rather than the [faster] Core 1) allows me to play back my 192kbps audio fine.

**Comment by cgreening** [comment]
I think the `tskIDLE_PRIORITY` could be an issue - that's the lowest priority so it may be that it just didn't get enough CPU time. Probably changing that to 1 would improve things quite a bit.

Either way - good job on fixing it!
